# The URL the site will be built for
base_url = "https://wheretopark.app"

description = "Where To Park is a parking lot assistant that helps you find the best free parking spot in the lot with the help of AI and real-time analysis"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "en"

generate_feed = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
minify_html = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
author = "Grzegorz gbaranski Baraski"
# Put all your custom variables here
juice_logo_name = "Where To Park"
juice_logo_path = "logo.svg"

[languages.pl]
title = "Where To Park - inteligentne systemy parkowania"

[languages.pl.translations]
flag = "叼"
exploreMore = "Zobacz wicej"
heading = "System parking贸w oparty na sztucznej inteligencji kt贸ry faktycznie zaoszczdzi czas!"
subheading = "U偶ywamy **sztucznej inteligencji** i **kamer monitoringowych** aby okreli zajto parking贸w w **czasie rzeczywistym**."
or = "lub"
openAppInBrowser = "otw贸rz aplikacj w przegldarce"

[languages.en]
title = "Where To Park - AI powered parking lot systems"

[languages.en.translations]
flag = ""
exploreMore = "Explore More"
heading = "An AI-powered parking lot solution that actually saves you time!"
subheading = "We use **Artificial Intelligence** and **CCTV Cameras** in order to determine parking lot occupancy in **real-time**."
or = "or"
openAppInBrowser = "open the app in browser"